Feat: 게시글 작성 api
potato-log/potato-log-be pull request #16
Opened 2024-05-17 09:21 UTC by chaseunghyeok

## PR 유형

- [ ] 버그 수정
- [ ] 새로운 기능 추가
- [ ] 코드 스타일 업데이트 (서식, 로컬 변수)
- [ ] 리팩터링 (기능 변경 없음, API 변경 없음)
- [ ] 빌드 관련 변경
- [ ] CI/CD 관련 변경
- [ ] 문서 내용 변경
- [ ] 기타... 설명:

## 이슈

이슈 번호: resolves #4

2024-05-18 03:42 UTC, JeYeongR requested changes
고생하셨어용~

2024-05-18 04:01 UTC, JeYeongR commented on src/main/java/site/potatolog/potatolog/post/controller/PostController.java
> +    public ResponseEntity<String> writePost(@RequestBody PostRequest postRequest) {
반환값으로 포스트아이디를 내보내는게 좋아보여요

2024-05-18 04:01 UTC, JeYeongR commented on src/main/java/site/potatolog/potatolog/post/domain/Post.java
> +    }
이건 진짜 잘했음~

2024-05-18 04:01 UTC, JeYeongR commented on src/main/java/site/potatolog/potatolog/post/dto/PostRequest.java
> +    private String tagContent;
태그를 배열로 받는게 좋아보여요

2024-05-18 04:01 UTC, JeYeongR commented on src/main/java/site/potatolog/potatolog/post/service/PostService.java
> +        tagRepository.save(tag);
cascade 설정하면 save할 때 같이 인서트가능!

2024-05-18 04:01 UTC, JeYeongR commented on src/main/java/site/potatolog/potatolog/post/service/PostService.java
> +    }
저장 로직을 다시 한번 생각해봐야 할듯

지금 로직에서는 태그를 계속 저장만 하는데 저러면 같은 태그가 여러개 생김
https://velog.io/@ljinsk3/%ED%95%B4%EC%8B%9C%ED%83%9C%EA%B7%B8-%EC%83%9D%EC%84%B1-API

2024-05-18 04:01 UTC, JeYeongR commented on src/main/java/site/potatolog/potatolog/post/dto/PostRequest.java
> +    private String imageUrl;
이미지 url은 postContent 안에 들어가 있음! 

포스트 임시글로 저장하고 만들어진 id로 imageUrl을 디비에 저장하는 api가 있어야할듯

2024-05-18 04:01 UTC, JeYeongR commented on src/main/java/site/potatolog/potatolog/post/domain/PostImage.java
> +    }
id는 필요없어요2

2024-05-18 04:01 UTC, JeYeongR commented on src/main/java/site/potatolog/potatolog/post/domain/Post.java
> +    }
id는 필요없어요

2024-05-18 04:05 UTC, JeYeongR commented on src/main/java/site/potatolog/potatolog/post/controller/PostController.java
> +        return new ResponseEntity<>("Success", HttpStatus.CREATED);
CommonResponse 사용해주세요
```java
return new ResponseEntity<>(CommonResponse.created(response), HttpStatus.CREATED);
```

2024-05-18 04:07 UTC, JeYeongR commented on src/main/java/site/potatolog/potatolog/post/controller/PostController.java
> +        return new ResponseEntity<>("Success", HttpStatus.CREATED);
사용 전:
<img width="77" alt="image" src="https://github.com/potato-log/potato-log-be/assets/113500815/523170c9-67bd-4411-bf39-57f2fcb1f6c5">


사용 후:
<img width="192" alt="image" src="https://github.com/potato-log/potato-log-be/assets/113500815/b88fe463-3bd8-41a5-9243-64bc591f0032">

2024-05-18 04:08 UTC, JeYeongR commented on src/main/java/site/potatolog/potatolog/post/controller/PostController.java
> +@RequestMapping("/post")
복수형으로 해주세요

2024-05-20 08:57 UTC, chaseunghyeok commented on src/main/java/site/potatolog/potatolog/post/controller/PostController.java
> +@RequestMapping("/post")
완료

2024-05-20 08:58 UTC, chaseunghyeok commented on src/main/java/site/potatolog/potatolog/post/controller/PostController.java
> +        return new ResponseEntity<>("Success", HttpStatus.CREATED);
👌

2024-05-20 08:58 UTC, chaseunghyeok commented on src/main/java/site/potatolog/potatolog/post/domain/Post.java
> +    }
👌

2024-05-20 08:58 UTC, chaseunghyeok commented on src/main/java/site/potatolog/potatolog/post/domain/PostImage.java
> +    }
👌

2024-05-20 08:59 UTC, chaseunghyeok commented on src/main/java/site/potatolog/potatolog/post/controller/PostController.java
> +    public ResponseEntity<String> writePost(@RequestBody PostRequest postRequest) {
👌

2024-06-05 05:23 UTC, closed without merging