Feature/#6
potato-log/potato-log-be pull request #17
Opened 2024-05-17 14:01 UTC by jeongjin01

## PR 유형

- [ ] 버그 수정
- [ ] 새로운 기능 추가
- [ ] 코드 스타일 업데이트 (서식, 로컬 변수)
- [ ] 리팩터링 (기능 변경 없음, API 변경 없음)
- [ ] 빌드 관련 변경
- [ ] CI/CD 관련 변경
- [ ] 문서 내용 변경
- [ ] 기타... 설명:

## 이슈

이슈 번호: resolves #6

2024-05-18 04:05 UTC, JeYeongR reviewed
서비스까지 다 만들면 남기겠음~~

2024-05-30 12:09 UTC, JeYeongR requested changes
로직은 너무 잘 동작함!! 고수 ㅇㅈ

2024-05-30 12:20 UTC, JeYeongR requested changes

2024-05-30 12:20 UTC, JeYeongR commented on src/main/java/site/potatolog/potatolog/user/controller/UserController.java
> +    public ResponseEntity<?> getUserInfo(@RequestParam(value = "code") String code) {
반환 타입 제대로 명시해주세요

2024-05-30 12:20 UTC, JeYeongR commented on src/main/java/site/potatolog/potatolog/user/controller/UserController.java
> +    }
서비스에서 해도 좋을 듯!

2024-05-30 12:20 UTC, JeYeongR commented on src/main/java/site/potatolog/potatolog/user/dto/UserRequest.java
> +                .email(html_url)
깃허브에서 주는 값 확인해보니 이메일이 없던데 이메일을 htmlUrl로 바꿔도 괜찮아보여요

2024-05-30 12:20 UTC, JeYeongR commented on src/main/java/site/potatolog/potatolog/user/dto/UserResponse.java
> +@AllArgsConstructor
고민해보고 추가해보시죠

2024-05-30 12:20 UTC, JeYeongR commented on src/main/java/site/potatolog/potatolog/user/service/UserService.java
> +        log.info("User: {}", userInfo);
로그찍는거 너무 좋은데 toString을 오버라이딩 안해서 그냥 주소값으로 나옴

2024-05-30 12:20 UTC, JeYeongR commented on src/main/java/site/potatolog/potatolog/user/controller/UserController.java
> +    @Autowired
승혁님은 @RequiredArgsConstructor 사용중인데 둘이 통일하시죠!

2024-05-30 12:20 UTC, JeYeongR commented on src/main/java/site/potatolog/potatolog/user/service/UserService.java
> +    private UserRepository userRepository;
final로 선언해주는 게 좋아요! 얘도 승혁님이랑 통일 필요

2024-05-31 17:26 UTC, jeongjin01 commented on src/main/java/site/potatolog/potatolog/user/dto/UserRequest.java
> +                .email(html_url)
이메일이 없어가지구 html_url로 깃허브 주소 들어가게 해뒀는데 컬럼 이름을 바꾸는게 나을까여?

2024-05-31 17:27 UTC, jeongjin01 commented on src/main/java/site/potatolog/potatolog/user/dto/UserRequest.java
> +                .email(html_url)
생각해보니까 주소인데 왜 이메일로 생각했는지 모르겠음

2024-06-01 02:13 UTC, JeYeongR commented on src/main/java/site/potatolog/potatolog/user/dto/UserRequest.java
> +                .email(html_url)
이메일 없으니 주소로 컬럼 이름 변경하죠!

2024-06-03 12:45 UTC, JeYeongR approved these changes
고수 ㅇㅈ

2024-06-03 12:45 UTC, merged