Feature/#4
potato-log/potato-log-be pull request #20
Opened 2024-06-05 06:44 UTC by chaseunghyeok

## PR 유형

- [ ] 버그 수정
- [ ] 새로운 기능 추가
- [ ] 코드 스타일 업데이트 (서식, 로컬 변수)
- [ ] 리팩터링 (기능 변경 없음, API 변경 없음)
- [ ] 빌드 관련 변경
- [ ] CI/CD 관련 변경
- [ ] 문서 내용 변경
- [ ] 기타... 설명:

## 이슈

이슈 번호: resolves #4

2024-06-06 16:07 UTC, JeYeongR requested changes
탭 크기 수정하고,  dev랑 머지한번하고 푸쉬해주세요.

2024-06-06 16:07 UTC, JeYeongR commented on src/main/java/site/potatolog/potatolog/PotatologApplication.java
> +@EnableJpaAuditing
하나 지워주세요

2024-06-06 16:07 UTC, JeYeongR commented on src/main/java/site/potatolog/potatolog/post/domain/Post.java
> +
탭크기 4로 정하지 않았나요?

2024-06-06 16:07 UTC, JeYeongR commented on src/main/java/site/potatolog/potatolog/post/dto/PostRequest.java
> +    String finalContent = this.isTemp ? this.postContent : this.postContent + "<img src=\"" + this.imageUrl + "\" />";
얘는 어디서 사용되나요?

2024-06-07 09:50 UTC, chaseunghyeok commented on src/main/java/site/potatolog/potatolog/post/domain/Post.java
> +
옙 수정하겠습니다

2024-06-07 09:51 UTC, chaseunghyeok commented on src/main/java/site/potatolog/potatolog/PotatologApplication.java
> +@EnableJpaAuditing
넵

2024-06-07 09:51 UTC, chaseunghyeok commented on src/main/java/site/potatolog/potatolog/post/dto/PostRequest.java
> +    String finalContent = this.isTemp ? this.postContent : this.postContent + "<img src=\"" + this.imageUrl + "\" />";
content에 이미지 저렇게 저장되게하려했는데 일단 지우겠습니다!

2024-06-07 12:46 UTC, JeYeongR commented on src/main/java/site/potatolog/potatolog/post/dto/PostRequest.java
> +    String finalContent = this.isTemp ? this.postContent : this.postContent + "<img src=\"" + this.imageUrl + "\" />";
finalContent 변수를 사용하는 곳이 없어서 물어본 거였어요!

2024-06-18 12:19 UTC, JeYeongR approved these changes

2024-06-18 12:19 UTC, merged